### ISSUE TITLE
stalls on vim start

### ISSUE THREAD

**Issue by codebutcher** [chris-morgan/tty-player#1]
The player stalls with the vim status-bar and a blank screen every time vim is run
The player then ceases to function due to a JS error

<img width="519" alt="screen shot 2015-08-13 at 08 19 43" src="https://cloud.githubusercontent.com/assets/1163784/9243077/7730dd36-4194-11e5-8a0c-7f6758d64dfb.png">

This issue was produced on chrome

The scenario generates the following JS error (in term.js):
<img width="1260" alt="screen shot 2015-08-13 at 08 48 28" src="https://cloud.githubusercontent.com/assets/1163784/9243366/60def8a2-4198-11e5-8d5a-506b09334b7a.png">

short analysis : term is receiving 23 lines of input in vi mode when screen height is 24 lines

**Comment by chris-morgan** [comment]
This looks like a term.js bug, but I’ll need a little more to diagnose is precisely.

Could you please post the following:
- a sample ttyrec file that demonstrates this;
- the specific version of term.js being used?

**Comment by codebutcher** [comment]
1. attaching a sample
2. using the term.js from the ttyplayer repo.

**Comment by chris-morgan** [comment]
(Attaching a .ttyrec file having failed, I was emailed the sample file.)

If you resize the tty-player to 180 columns wide, it works. It’s failing when it sends <code><kbd>ESC</kbd>[23;1H~<em>«178 spaces»</em></code>, so it’s a simple overflow that term.js isn’t coping with—79 spaces on line 23, 80 on line 24, then it’s off the screen for the final 19 spaces.

If you use termrec for recording, it includes the width and height in the ttyrec script (you need to use a version of term.js including chjj/term.js#75 for it to work), so you wouldn’t run into this issue. You can also go specifying the `cols` and `rows` attributes on the tty-player element.

As for the exception itself, I was able to reduce it very effectively and have filed chjj/term.js#84 for the matter. As it is a term.js issue and not a tty-player issue (with the way of achieving the desired behaviour explained in the previous paragraph also), I am closing this issue.
