### ISSUE TITLE
adjusting speed?

### ISSUE THREAD

**Issue by zotherstupidguy** [chris-morgan/tty-player#5]
is there of adjusting replay speed from the tty-player?

**Comment by chris-morgan** [comment]
Yes; that’s the `playbackRate` property, just as with `<video>`.

**Comment by zotherstupidguy** [comment]
I am having trouble adjusting tty-player tag, I set playbackRate = "0.1" and not getting any difference with speed even with different values. any idea what i could be missing?

**Comment by zotherstupidguy** [comment]
I am having trouble adjusting tty-player tag, I set playbackRate = "0.1" and not getting any difference with speed even with different values. any ideas what i could be missing?

**Comment by zotherstupidguy** [comment]
I am having trouble adjusting tty-player tag, I set playbackRate = "0.1" and not getting any difference with speed even with different values. any ideas what i could be missing?

**Comment by zotherstupidguy** [comment]
I am having trouble adjusting tty-player tag, I set playbackRate = "0.1" and not getting any difference with speed even with different values. any ideas what i could be missing?

**Comment by chris-morgan** [comment]
It’s an IDL attribute, a property set through JavaScript, i.e. `video.playbackRate = 0.1`. You can’t change the value through a content attribute (viz. `<tty-player playbackRate="0.1">` doesn’t work).

**Comment by zotherstupidguy** [comment]
i am changing it inside the tty-player.js file and it works, but it affects all the tty-players on a page, so is there a better way, to make it adjustable per each tty-player??

**Comment by chris-morgan** [comment]
It’s a property on each tty-player element, just like with HTMLVideoElement. Remember, tty-player.js is a drop-in replacement for the video element, you do things just the same way as you would do with a video element. For example, to change the playback rate of the first tty-player in the document, `document.querySelector("tty-player").playbackRate = 0.1`.

**Comment by zotherstupidguy** [comment]
OK, Thanks again!! i apologize for my weak front-end knowledge :) 

Shall give it a try :+1:  :+1:  :+1:
